apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: tekton-triggers-github-sa
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret # the secret with token
                secretKey: secretToken
            - name: "eventTypes"
              value: [ "push" ] # only push event
      bindings:
        - ref: github-binding # TriggerBinding with params
      template:
        ref: github-template # TriggerTemplate